name: Manual Test Workflow
on: workflow_dispatch

jobs:
  FirstJob:
    runs-on: ubuntu-latest
    steps:
      - 
        name: set lower case repository name
        run: |
          echo "REPOSITORY_LC=${REPOSITORY,,}" >>${GITHUB_ENV}
        env:
          REPOSITORY: '${{ github.repository }}'
      - 
        name: Login to github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Show all env variables
        run: env
      -
        name: Show current tag
        run: ${{github.ref_name}}
      - 
        name: Build and Push dockerimage
        uses: docker/build-push-action@v3
        with:
          file: src/DockerFiles/TestHelloWorld.dockerfile
          push: true
          tags: ghcr.io/${{ env.REPOSITORY_LC }}/test-image:latest