name: Manual Test Workflow
on: workflow_dispatch

jobs:
  FirstJob:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and Push dockerimage
        uses: docker/build-push-action@v3
        with:
          file: src/DockerFiles/TestHelloWorld.dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/test-image:latest